### ISSUE TITLE
ARIA Labels não estão dinâmicos

### ISSUE THREAD

**Issue by brunopulis** [lucasferreiralimax/criarcurriculo#10]
## Sumário 
Atributos aria-label estão estáticos, prejudicando a acessibilidade do sistema

## Passos para reprodução
* Acessar a aplicação na sessão de Telefone
* Inspecionar o botão de **Menos**, o resultado do `aria-label` dele será `aria-label="Remover e-mail"`

## Comportamento esperado
O atributo aria-label deveria ser dinâmico de acordo com a sessão que o usuário está preenchendo. 

Como você desenvolveu o preenchimento do aria-label através de strings de i18n fixas com o valor de:

> No caso de remoção
`:aria-label="$t('aria-label.email_remove')"` 

> No caso de adição
`:aria-label="$t('aria-label.email_add')"`

Ele irá repetir os valores de "Remover e-mail" e "Adicionar e-mail" em todos os inputs com essa propriedade.

**Comment by lucasferreiralimax** [comment]
Olá @brunopulis seja bem-vindo e muito obrigado pela contribuição.

Segue [merge da solução](https://github.com/lucasferreiralimax/curriculogratis/pull/12) para esses labels que você informou, aproveitei para colocar o texto que o usúario insere como complemento para o label do botão informando ainda mais a descrição do mesmo.

**Comment by brunopulis** [comment]
@lucasferreiralimax muito bom cara! :)
