### ISSUE TITLE
Forms separados por fieldset

### ISSUE THREAD

**Issue by brunopulis** [lucasferreiralimax/criarcurriculo#11]
## Sumário
Formulário não utilizado os fieldset para definir uma separação lógica
 
## Passos para reprodução
* Inspecionar o formulário
* Verificar o uso da tag `fieldset` e `legend`

## Comportamento esperado
Cada sessão do formulário deveria conter um `fieldset` e `legend`, assim, a estrutura lógica ficaria de modo padronizado e ajudaria em questões de acessibilidade. 

O fieldset e legend contribuem para que seu formulário fique mais semântico e acessível

**Comment by lucasferreiralimax** [comment]
Foi adicionado os fieldset e legend nos componente box com os valores de input de valores

**Comment by lucasferreiralimax** [comment]
@brunopulis muito obrigado pelo o feedback e colaboração, me sinto grato em conseguir aplicar essa melhoria.
